### ISSUE TITLE
show node labels behavior changed

### ISSUE THREAD

**Issue by goessner** [goessner/mec2#17]
Is this intended in contrast to former behavior ?

Is it possible to set show properties inside of JSON description ?

**Comment by jauhl** [comment]
How has the behaviour changed? I simply moved the flags and renamed some of them. (Edit: This flag is now `true` by default if you mean that.) See
https://github.com/goessner/mec2/blob/761ddc714834940556efb1da227feb4a4be461b4/src/mec.core.js#L83-L186

It is not possible to set show properties inside the model since we agreed that models should be strictly graphics agnostic. You can however set a user defined show object for your instance elsewhere.

When extending model with `mec.model.extend()` you still pass the model itself but now you can an optional second parameter, the namespace your model is defined in. This namespace will be set as a reference in `model.env`. If the namespace you pass already has a property `show`, it is expected to be a **complete!** user defined show object and `mec.show` will not be copied. Complete means that it currently must contain all properties from `mec.show`, regardless is they have different values or not.

If you don’t pass a second parameter in `mec.model.extend()` all methods default to `mec.show` and changes in colors and flags are global and not per instance.

**Comment by goessner** [comment]
Yes ... the default value is `true` now. That's what I mean.

I recognized the additional parameter of the extend method. Though my first reaction was, to prefer adding it to the `init` method, I now agree, that it is ok that way.
