### ISSUE TITLE
Issues with mec.view.chart

### ISSUE THREAD

**Issue by goessner** [goessner/mec2#24]
* `model` is undefined (L. 400)
* after having resolved this, `preview` mode works without an animated point running along the graph... as it should.
* Why are the `mec2` data points copied over to the `g2.chart` data points in the inner animation loop ... no way to avoid this ?
* what does that double ` e.data.shift(); e.data.shift();` mean ?
* `asJSON`  exports old syntax.
* source code is quite hard to understand ... think *long term maintainance*.

**Comment by klawr** [comment]
- Haven't experimented much with validate. Should be `this.model`. I'll update shortly.
- Is not implemented yet, since i had open questions like: should i just assume that the user chose the timing and drive speed correctly? There is no point if that is not the case but also hard to test...
- I have to pick the y-value for each x-value seperately, therefore I can't just pipe mec2's value through. Or at least i haven't found a way to do so.
- This is to remove the x and y value from the data array in dynamic mode.
- `type` is changed to `as` in next commit
- Will add comments to code

**Comment by klawr** [comment]
If i missed something, please let me know.

Please note that the nods are currently only reappearing for values that "start again" like an angle which
wanders between 0 and 360 degrees. A nod for a timer just appears once between t0 and t0+Dt.
If that is wanted, i can try to implement that, but I haven't found a way to do so in a reliable way...
