### ISSUE TITLE
invalid models are destroyed

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#3]
When defining an invalid model with dof = -1, it completely collapses to the origin when trying move/solve it. See this standard fourbar with three basenodes:
![grafik](https://user-images.githubusercontent.com/19715408/43688285-174e51d0-98e6-11e8-9405-fc3df9a278ea.png)
This is critical when it happens during editing of the model because it cannot be reverted and the model has to be discarded.

**Comment by goessner** [comment]
Bin grad offline ... hab aber noch einige Bugfixes auf Github gestellt..



Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: jauhl <notifications@github.com> Datum: 05.08.18  19:32  (GMT+01:00) An: goessner/mec2 <mec2@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [goessner/mec2] invalid models are destroyed (#3) 
When defining an invalid model with dof = -1, it completely collapses to the origin when trying move/solve it. See this standard fourbar with three basenodes:



This is critical when it happens during editing of the model because it cannot be reverted and the model has to be discarded.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/goessner/mec2","title":"goessner/mec2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/goessner/mec2"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"invalid models are destroyed (#3)"}],"action":{"name":"View Issue","url":"https://github.com/goessner/mec2/issues/3"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/goessner/mec2/issues/3",
"url": "https://github.com/goessner/mec2/issues/3",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "invalid models are destroyed (#3)",
"sections": [
{
"text": "",
"activityTitle": "**jauhl**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jauhl",
"facts": [
{
"name": "Repository: ",
"value": "goessner/mec2"
},
{
"name": "Issue #: ",
"value": 3
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"goessner/mec2\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"goessner/mec2\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/goessner/mec2/issues/3"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 364764196\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by goessner** [comment]
Can you publish the corresponding model ?

**Comment by jauhl** [comment]
This simple fourbar initializes okayish. But try dragging (or simply clicking) node A.
```javascript
{
    id: '4bar',
    nodes: [
        {id:'A0',x:100,y:100,base:true},
        {id:'A',x:100,y:150},
        {id:'B',x:350,y:220,base:true},
        {id:'B0',x:300,y:100,base:true},
    ],
    constraints: [
        { id:'a',p1:'A0',p2:'A',len:{type:'const'} },
        { id:'b',p1:'A', p2:'B',len:{type:'const'} },
        { id:'c',p1:'B0', p2:'B',len:{type:'const'} },
    ]
}
```

This fourbar with a reference doesn't even initialize:

```javascript
{
    id: '4bar',
    nodes: [
        {id:'A0',x:100,y:100,base:true},
        {id:'A',x:100,y:150},
        {id:'B',x:350,y:220,base:true},
        {id:'C',x:250,y:250},
        {id:'B0',x:300,y:100,base:true},
    ],
    constraints: [
        { id:'a',p1:'A0',p2:'A',len:{type:'const'} },
        { id:'b',p1:'A', p2:'B',len:{type:'const'} },
        { id:'c',p1:'B0', p2:'B',len:{type:'const'} },
        { id:'d',p1:'B', p2:'C',len:{type:'const'},ori:{type:'ref',ref:'b'} }
    ]
}
```

**Comment by goessner** [comment]
.. even this simple model doesn't compile properly ..
```js
{
    id: 'overconstrained',
    nodes: [
        {id:'A0',x:100,y:100,base:true},
        {id:'B0',x:300,y:100,base:true},
    ],
    constraints: [
        { id:'a',p1:'A0',p2:'B0',len:{type:'const'} },
    ]
}
```
Compilation needs to get more robust ... hmm.

Nodes are jumping to origin, when coordinates get NaN value.

**Comment by goessner** [comment]
All models above share the pathological case, where a constraint is defined between two base nodes.

The constraint mass becomes infinite then.

Now .. resolving the bug .. the constraint mass is set to `0` in this case.
